name: Build

on:
  push:
    branches:
      - master
      - '*.x'

jobs:
  build:
    name: .NET Build
    uses: sketch7/workflows/.github/workflows/build-and-publish.yml@main
    with:
      dotnet-version: 6.0.x