name: Build

on:
  push:
    branches:
      - master
      - '*.x'

  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish NuGet packages'
        required: true
        default: 'false'

jobs:
  build:
    name: Build
    uses: sketch7/workflows/.github/workflows/build-and-publish.yml@main
    with:
      dotnet-version: 6.0.x