name: App Build

on:
  push:
    branches:
      - master
      - '*.x'
      - feature/* # todo: comment

  # todo: uncomment
  # pull_request:
  #   branches:
  #     - master
  #     - '*.x'

jobs:
  build_app:
    name: App Build Job x33
    uses: sketch7/.github/.github/workflows/dotnet-publish.yml@feature/reusable-workflow-setup
    with:
      dotnet-version: 6.0.x
      publishable: ${{ contains(fromJSON('["develop", "master", "workflow", "feature/reusable-workflow"]'), github.ref_name) || endsWith(github.ref_name, '.x')  }}
    secrets:
      nuget-auth-token: ${{ secrets.NUGET_KEY }}
  ver:
    runs-on: ubuntu-latest
    needs: build_app
    steps:
      - run: echo ${{ needs.build_app.outputs.version }}

