name: App Build

on:
  push:
    branches:
      - master
      - '*.x'
      - feature/*

  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish NuGet packages'
        required: true
        default: 'false'

jobs:
  build:
    name: App Build Job
    uses: sketch7/.github/.github/workflows/dotnet-publish.yml@feature/reusable-workflow-setup
    with:
      dotnet-version: 6.0.x