name: App Build

on:
  push:
    branches:
      - master
      - '*.x'
      - feature/*

  # pull_request:
  #   branches:
  #     - master
  #     - '*.x'

  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish NuGet packages'
        required: true
        default: 'false'

jobs:
  build_app:
    name: App Build Job x25
    uses: sketch7/.github/.github/workflows/dotnet-publish.yml@feature/reusable-workflow-setup
    with:
      dotnet-version: 6.0.x
      publishable: ${{ github.ref_name == 'develop' || github.ref_name == 'master' || endsWith(github.ref_name, '.x') }}
